name: BAKE MY DAY
favicon: null
layout_spectrum: 0.0419809150043875
typography_spectrum: 0.9806250492110848
title: BAKE MY DAY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#664e41'
    - '#c8df8d'
    - '#f07fb3'
    - '#b2a49a'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
