name: BAKE MY DAY
favicon: null
layout_spectrum: 0.51169
typography_spectrum: 0.50835
title: BAKE MY DAY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#664e41'
    - '#c8df8d'
    - '#f07fb3'
    - '#b2a49a'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
